version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    network_mode: "host"  # Использовать сеть хоста
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    network_mode: "host"  # Использовать сеть хоста

